services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - PORT=3000
    env_file: .env
    depends_on:
      api:
        condition: service_healthy
    restart: on-failure
    networks:
      - streamcurl-net

  api:
    build:
      context: ./backend
    ports: ["8001:8000"]
    volumes:
      - ./backend:/app
      - ./backend/media:/media
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://user:password@db/mydatabase
      - REDIS_URL=redis://redis:6379
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/v1/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - streamcurl-net

  celery_worker:
    build:
      context: ./backend
    command: /bin/bash -c "mkdir -p /app/media/hls /app/media/temp && celery -A app.workers.stream_tasks worker --loglevel=info"
    user: root
    volumes:
      - ./backend:/app
      - ./backend/media:/media
    env_file: .env
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@db/mydatabase
      - REDIS_URL=redis://redis:6379
    restart: on-failure
    networks:
      - streamcurl-net

  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - streamcurl-net

  redis:
    image: redis:6-alpine
    networks:
      - streamcurl-net

networks:
  streamcurl-net:
    driver: bridge
