"""add started_at to stream model

Revision ID: 1d1df0ea8358
Revises: d0a6dd5c6a91
Create Date: 2025-07-29 02:06:12.893625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1df0ea8358'
down_revision: Union[str, Sequence[str], None] = 'd0a6dd5c6a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streams', sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streams', 'started_at')
    # ### end Alembic commands ###
