"""Ubah bidang youtube di model stream

Revision ID: 5d8d599a8b2b
Revises: a9a8db4c4ab4
Create Date: 2025-07-29 09:13:53.770977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8d599a8b2b'
down_revision: Union[str, Sequence[str], None] = 'a9a8db4c4ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streams', sa.Column('youtube_video_id', sa.String(length=255), nullable=True))
    op.add_column('streams', sa.Column('youtube_live_viewers', sa.Integer(), nullable=True))
    op.drop_column('streams', 'youtube_video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streams', sa.Column('youtube_video_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('streams', 'youtube_live_viewers')
    op.drop_column('streams', 'youtube_video_id')
    # ### end Alembic commands ###
