"""manual add gdrive fields to user and update config

Revision ID: 60ab1abe8e9e
Revises: b11b40b83a2b
Create Date: 2025-07-20 07:35:15.535021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ab1abe8e9e'
down_revision: Union[str, None] = 'b11b40b83a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gdrive_folder_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('gdrive_quota_gb', sa.Integer(), nullable=False, server_default='50'))
    op.add_column('users', sa.Column('gdrive_usage_bytes', sa.BigInteger(), nullable=False, server_default='0'))
    
    op.drop_column('google_drive_config', 'drive_folder_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_drive_config', sa.Column('drive_folder_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    op.drop_column('users', 'gdrive_usage_bytes')
    op.drop_column('users', 'gdrive_quota_gb')
    op.drop_column('users', 'gdrive_folder_id')
    # ### end Alembic commands ###
