"""Add cpu and ram to vps table

Revision ID: 7754b7dcd8fa
Revises: 811ec80b7171
Create Date: 2025-07-20 02:34:13.084325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7754b7dcd8fa'
down_revision: Union[str, Sequence[str], None] = '811ec80b7171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vps', sa.Column('cpu_cores', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('vps', sa.Column('ram_gb', sa.Integer(), nullable=False, server_default='2'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vps', 'ram_gb')
    op.drop_column('vps', 'cpu_cores')
    # ### end Alembic commands ###
