"""Initial migration

Revision ID: 811ec80b7171
Revises: 
Create Date: 2025-07-20 02:32:55.817961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811ec80b7171'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vps', sa.Column('cpu_cores', sa.Integer(), nullable=False))
    op.add_column('vps', sa.Column('ram_gb', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vps', 'ram_gb')
    op.drop_column('vps', 'cpu_cores')
    # ### end Alembic commands ###
