"""add download progress to stream

Revision ID: a9a8db4c4ab4
Revises: 1d1df0ea8358
Create Date: 2025-07-29 06:20:30.465513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a8db4c4ab4'
down_revision: Union[str, Sequence[str], None] = '1d1df0ea8358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streams', sa.Column('download_progress', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streams', 'download_progress')
    # ### end Alembic commands ###
