"""Add GoogleDriveConfig and update media models

Revision ID: b11b40b83a2b
Revises: 7754b7dcd8fa
Create Date: 2025-07-20 12:12:33.527116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11b40b83a2b'
down_revision: Union[str, Sequence[str], None] = '7754b7dcd8fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_drive_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('drive_folder_id', sa.String(length=255), nullable=True),
    sa.Column('account_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_drive_config_id'), 'google_drive_config', ['id'], unique=False)
    op.add_column('audios', sa.Column('storage_type', sa.String(length=50), nullable=False, server_default='local'))
    op.add_column('audios', sa.Column('gdrive_file_id', sa.String(length=255), nullable=True))
    op.alter_column('audios', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('audios', 'filepath',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.add_column('overlays', sa.Column('storage_type', sa.String(length=50), nullable=False, server_default='local'))
    op.add_column('overlays', sa.Column('gdrive_file_id', sa.String(length=255), nullable=True))
    op.alter_column('overlays', 'filepath',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.add_column('videos', sa.Column('storage_type', sa.String(length=50), nullable=False, server_default='local'))
    op.add_column('videos', sa.Column('gdrive_file_id', sa.String(length=255), nullable=True))
    op.alter_column('videos', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('videos', 'filepath',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'filepath',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('videos', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('videos', 'gdrive_file_id')
    op.drop_column('videos', 'storage_type')
    op.alter_column('overlays', 'filepath',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.drop_column('overlays', 'gdrive_file_id')
    op.drop_column('overlays', 'storage_type')
    op.alter_column('audios', 'filepath',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('audios', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('audios', 'gdrive_file_id')
    op.drop_column('audios', 'storage_type')
    op.drop_index(op.f('ix_google_drive_config_id'), table_name='google_drive_config')
    op.drop_table('google_drive_config')
    # ### end Alembic commands ###
